name: Deploy Hangry Hippo Frontend to Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
jobs:
  function_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Run functional tests
        run: npm test -- --coverage --watchAll=false
  deploy:
    needs: [function_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
      - name: Generate deployment package
        run: zip -r deploy.zip build Dockerfile
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${ secrets.AWS_IAM_ROLE }
          role-session-name: AWS_SESSION_TOKEN
          aws-region: us-east-1
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_session_token: AWS_SESSION_TOKEN
          application_name: hangry-web
          environment_name: Hangryweb-env
          version_label: ${{ GITHUB.RUN_ID}}
          region: us-east-1
          deployment_package: frontend/deploy.zip
  acceptance_test:
    needs: [deploy]
    runs-on: ubuntu-latest
    container: cypress/included:10.3.0
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - run: cypress run --config-file=cypress.config.js
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: frontend/cypress/videos
  security_test:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Dynamic Application Security Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://hangry-web-dev.us-east-1.elasticbeanstalk.com/'
