name: Lesson 5 DAST

on:
  push:
    branches:
      - lesson-5
      - new-main

jobs:
  function_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Run functional tests
        run: npm test -- --coverage --watchAll=false
  deploy:
    needs: [function_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
      - name: Generate deployment package
        run: zip -r deploy.zip build Dockerfile
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment
